# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_LLqeWuxkmOB2049xhXi1BBL1mPdGct
"""

import streamlit as st
import pickle
import numpy as np

# Load Model & Scaler
model = pickle.load(open('model_ann.pkl', 'rb'))
scaler = pickle.load(open('scaler.pkl', 'rb'))  # kalau kamu pakai scaler
# Kalau ada encoder juga tinggal load

st.title("Prediksi Resiko Diabetes")
st.write("Aplikasi ini digunakan untuk memprediksi resiko seseorang terkena diabetes berdasarkan data yang dimasukkan.")

# Input User
gender = st.selectbox("Jenis Kelamin", ["Perempuan", "Laki-Laki"])
age = st.number_input("Usia", min_value=1)
hypertension = st.selectbox("Hipertensi", ["Tidak", "Ya"])
heart_disease = st.selectbox("Penyakit Jantung", ["Tidak", "Ya"])
smoking_history = st.selectbox("Riwayat Merokok", ["Tidak Pernah", "Dulu Pernah", "Sekarang Merokok"])
bmi = st.number_input("BMI")
hba1c_level = st.number_input("HbA1c Level")
blood_glucose_level = st.number_input("Blood Glucose Level")

# Proses ke numerik sesuai data latih
data = np.array([
    1 if gender == "Laki-Laki" else 0,
    age,
    1 if hypertension == "Ya" else 0,
    1 if heart_disease == "Ya" else 0,
    {"Tidak Pernah": 0, "Dulu Pernah": 1, "Sekarang Merokok": 2}[smoking_history],
    bmi,
    hba1c_level,
    blood_glucose_level
]).reshape(1, -1)

# Scaling (jika pakai)
data_scaled = scaler.transform(data)

# Prediksi
if st.button("Prediksi"):
    prediction = model.predict(data_scaled)
    hasil = "Berisiko Diabetes" if prediction[0] == 1 else "Tidak Berisiko Diabetes"
    st.subheader(f"Hasil Prediksi : {hasil}")